import Link from "next/link";
import { notFound } from "next/navigation";

type Item={title:string;body:string;tags?:string[]};
const strengths:Item[]=[
 {title:"Software Engineering",body:"Backend systems, REST APIs, databases, integration, testing and production troubleshooting."},
 {title:"Enterprise Systems",body:"Authentication, SSO, operational controls and cross-system delivery in regulated environments."},
 {title:"Production & MLOps",body:"Kubernetes-based MLOps environments, observability, deployment validation and incident analysis."},
 {title:"AI Systems",body:"RAG, agents, MCP, evaluation and security—built as measurable system capabilities."}
];
const roadmap=[
 ["01","Python for AI","Typing, Pydantic, async, FastAPI, pytest","IN PROGRESS"],
 ["02","RAG Foundations","Ingestion, embeddings, citations, retrieval datasets","NEXT"],
 ["03","Hybrid Retrieval","BM25, vector search, reranking and Recall@K","PLANNED"],
 ["04","Agents & MCP","State, tool calling, permissions and MCP servers","PLANNED"],
 ["05","Evaluation","Task datasets, deterministic graders and regression CI","PLANNED"],
 ["06","Production AI","Security, tracing, Kubernetes and operational runbooks","PLANNED"]
];
const projects=[
 {status:"BUILDING · V0.2",title:"Enterprise Knowledge & Operations Agent",body:"A production-oriented agent with document ingestion, vector retrieval, reranking, citations and approval-gated operational tools.",tags:["FastAPI","Vector Search","Reranking","Agents","Security"],href:"/projects/enterprise-ai-agent-platform"},
 {status:"PLANNED · 02",title:"Voice Schedule Agent",body:"A Korean voice-to-calendar workflow that detects ambiguity, prevents duplicate actions and confirms high-impact changes before execution.",tags:["Speech","Temporal NLP","Agents","Evaluation"],href:"/projects/voice-schedule-agent"},
 {status:"SUPPORTING LAB · 03",title:"Agent Evaluation Lab",body:"Reusable datasets and graders for retrieval quality, tool selection, task success, regression, latency and cost.",tags:["Evals","Regression","Observability"],href:"/projects/agent-evaluation-lab"}
];

function Label({children}:{children:React.ReactNode}){return <p className="eyebrow">{children}</p>}
function Hero({label,title,body}:{label:string;title:string;body:string}){return <section className="page-hero"><Label>{label}</Label><h1>{title}</h1><p className="lede">{body}</p></section>}
function Cards({items}:{items:Item[]}){return <div className="card-grid">{items.map(i=><article className="card" key={i.title}><h3>{i.title}</h3><p>{i.body}</p>{i.tags&&<div className="tags">{i.tags.map(t=><span key={t}>{t}</span>)}</div>}</article>)}</div>}

function Home(){return <main>
 <section className="home-hero"><div><Label>SOFTWARE ENGINEER → AI SYSTEMS & AGENT ENGINEER</Label><h1>Building AI systems that work <em>beyond the demo.</em></h1><p className="lede">I connect AI intelligence with enterprise data, tools and workflows—then make the result measurable, secure and operable.</p><div className="actions"><Link className="button" href="/projects">View engineering proof</Link><Link className="text-link" href="/journey">Explore the journey →</Link></div></div><aside className="focus"><span>CURRENT BUILD · V0.2</span><h2>Enterprise Knowledge & Operations Agent</h2><p>Ingestion · Vector Search · Reranking · Citations · Approval Gates</p><div className="progress"><i /></div><small>Retrieval vertical slice implemented</small></aside></section>
 <section><Label>WHAT I BRING</Label><h2>A software engineering foundation for production AI.</h2><Cards items={strengths}/></section>
 <section className="statement"><Label>CAREER THESIS</Label><blockquote>I want to become the engineer who can connect AI intelligence with real systems, measure whether it works, and make it safe enough to matter.</blockquote></section>
 <section><div className="section-head"><div><Label>FEATURED WORK</Label><h2>Proof over claims.</h2></div><Link className="text-link" href="/projects">All projects →</Link></div><div className="project-grid">{projects.slice(0,2).map(ProjectCard)}</div></section>
 </main>}
function ProjectCard(p:typeof projects[number]){return <Link className="project-card" href={p.href} key={p.title}><span>{p.status}</span><h3>{p.title}</h3><p>{p.body}</p><div className="tags">{p.tags.map(t=><b key={t}>{t}</b>)}</div><strong>Read case study →</strong></Link>}
function Journey(){return <main><Hero label="JOURNEY" title="From building software to building intelligent systems." body="A cumulative record of what I learned, built, measured and changed at each stage."/><div className="timeline">{[
 ["FOUNDATION","Software Engineering","Enterprise applications, APIs, databases, authentication, testing and production constraints."],
 ["2026 · IN PROGRESS","Enterprise MLOps & Production","Kubernetes workloads, observability, security review and evidence-driven environment analysis."],
 ["CURRENT","AI Foundations","Python, machine learning, PyTorch and transformer mechanics built without hiding behind abstractions."],
 ["NEXT","RAG & Agent Engineering","Trusted retrieval, bounded tools, MCP, state and context engineering."],
 ["TARGET","Production AI Systems","Evaluation, security, observability, deployment and failure recovery."]
 ].map(([date,title,body],i)=><article key={title}><div><span>0{i+1}</span><small>{date}</small></div><div><h2>{title}</h2><p>{body}</p></div></article>)}</div></main>}
function Roadmap(){return <main><Hero label="ROADMAP" title="Learn it. Build it. Prove it." body="A topic is complete only when I can explain, implement, test, measure and use it inside a larger system."/><div className="roadmap">{roadmap.map(([n,t,b,s])=><article key={n}><div><strong>{n}</strong><span className="status">{s}</span></div><h2>{t}</h2><p>{b}</p><ul><li>LEARN the mechanism</li><li>BUILD a working slice</li><li>PROVE it with tests and metrics</li></ul></article>)}</div></main>}
function Projects(){return <main><Hero label="PROJECTS" title="Proof over claims." body="Each project exposes the problem, constraints, decisions, measurements, failures and reusable lessons."/><div className="project-grid">{projects.map(ProjectCard)}</div></main>}
function Experience(){return <main><Hero label="EXPERIENCE" title="Enterprise engineering shaped by production constraints." body="My background compounds with AI systems engineering through integration, reliability, security and cross-system problem solving."/><section className="experience"><aside><span>CURRENT / RECENT</span><h2>Software Developer</h2><p>INNODIGM · Seoul<br/>May 2020–Present</p></aside><div><ul><li>Develop and support enterprise applications and integrations across backend services, REST APIs and relational databases.</li><li>Contributed within a Kubernetes-based enterprise MLOps environment using Oracle/Exadata and observability tooling.</li><li>Supported authentication/SSO, employee-system integration, access controls, alerting and deployment validation.</li><li>Investigated production issues through environment comparison, workload behavior, resource conditions and application logs.</li><li>Prepared integration, system and acceptance-test evidence and security-review artifacts.</li></ul><div className="education"><h3>Queensland University of Technology</h3><p>Bachelor of Information Technology · Brisbane, Australia</p><h3>ACS Professional Year Program</h3><p>Professional development · Brisbane, Australia</p></div></div></section></main>}
function About(){return <main><Hero label="ABOUT" title="Software engineer by foundation. AI systems engineer by direction." body="I am Henry Woo, a software developer based in Seoul with professional experience across Australia and South Korea."/><section className="prose"><p>Working in a Kubernetes-based enterprise MLOps environment changed how I think about AI: a successful model is only one component of a successful system.</p><p>I focus on the engineering questions that appear after a prototype works—permissions, integration, evaluation, observability, failure recovery, security and the gap between development and production.</p><Cards items={[{title:"Understand before abstracting",body:"Learn the mechanism before hiding it behind a framework."},{title:"Build after learning",body:"Turn concepts into working systems and reusable evidence."},{title:"Measure before claiming",body:"Prefer repeatable evaluation over demo-driven confidence."},{title:"Design for failure",body:"Treat recovery and operations as product features."}]}/></section></main>}
function ProjectDetail({kind}:{kind:string}){const p=projects.find(x=>x.href.endsWith(kind));if(!p)return notFound();const isMain=kind==="enterprise-ai-agent-platform";return <main><Hero label={p.status} title={p.title} body={p.body}/><div className="tags hero-tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><section><Label>THE PROBLEM</Label><h2>{isMain?"The difficult part starts after the chatbot works.":"Reliable automation starts with explicit uncertainty."}</h2><p className="lede">{isMain?"Enterprise AI requires authentication, permissions, retrieval quality, tool failure handling, approvals, traceability, latency and security to be visible and measurable.":"The system must know when it has enough information to act, when to clarify and how to prevent duplicate or unintended operations."}</p></section>{isMain&&<section><Label>IMPLEMENTATION STATUS</Label><h2>A working retrieval vertical slice, then production depth.</h2><Cards items={[{title:"Shipped · Foundation",body:"Typed FastAPI endpoints, allow-listed tools, approval gates, Docker and CI."},{title:"Shipped · Retrieval v0.2",body:"Document ingestion, deterministic embeddings, cosine vector search, reranking and scored citations."},{title:"Next · Production RAG",body:"Semantic embeddings, pgvector, BM25 hybrid retrieval, access filters and Recall@K evaluation."},{title:"Then · Agent Operations",body:"MCP tools, durable approvals, audit events, tracing, Kubernetes deployment and failure drills."}]}/></section>}<section><Label>SUCCESS CRITERIA</Label><Cards items={[{title:"Task success",body:"Measured across a repeatable, versioned evaluation dataset."},{title:"Tool accuracy",body:"Correct tool and validated arguments for each task."},{title:"Quality",body:isMain?"Recall@K, MRR and citation-grounded answer checks.":"Intent/entity accuracy, clarification rate and duplicate prevention."},{title:"Operations",body:"P50/P95 latency, failure paths, traces and recovery evidence."}]}/></section><section><Label>DELIVERY STANDARD</Label><div className="proof-list"><span>Working repository</span><span>Automated tests</span><span>Evaluation report</span><span>Architecture decisions</span><span>Demo video</span><span>Known limitations</span></div></section></main>}

export default async function Page({params}:{params:Promise<{slug?:string[]}>}){const {slug=[]}=await params;const path=slug.join("/");if(!path)return <Home/>;if(path==="journey")return <Journey/>;if(path==="roadmap")return <Roadmap/>;if(path==="projects")return <Projects/>;if(path==="experience")return <Experience/>;if(path==="about")return <About/>;if(slug[0]==="projects"&&slug[1])return <ProjectDetail kind={slug[1]}/>;return notFound();}
